version: "2.4"
#### Services ####
services:
  #### MQTT-Service ####
  mqtt-service:
    build:
      context: ./src/mqtt-service
    image: mqtt-service:1.0.0
    restart: unless-stopped
    depends_on:
      - influxdb
    networks:
      - proxy-redirect
      - app-net
    volumes:
      - "./publish/:/publish/"
      - "./cfg-data/:/cfg-data/"
    mem_limit: 100mb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  #### Dashboard & Database InfluxDB ####
  influxdb:
    build:
      context: ./src/influxdb
    image: database_influxdb:2.6.1-alpine
    restart: unless-stopped
    volumes:
      - data-storage:/var/lib/influxdb2
    networks:
      - app-net
    ports:
      - "33000:8086"
    mem_limit: 250mb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=changeMe1!
      - DOCKER_INFLUXDB_INIT_ORG=edge
      - DOCKER_INFLUXDB_INIT_BUCKET=databus_values
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=industrialedge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#### Volumes ####
volumes:
  data-storage:
    name: data-storage

#### Network ####
networks:
  proxy-redirect:
    external: true
    name: proxy-redirect
  app-net:
    name: app-net
